  name: Run tests and upload to Codecov

  on:
    pull_request:
      branches: [main]
    workflow_dispatch:

  concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

  jobs:
    ci:
      uses: Dev-kitx/.github/.github/workflows/run-npm-vite-tests.yml@main
      secrets: inherit
      with:
        codecov_slug: Dev-Kitx/vscode-npm-play
